---
name: Reports Sandbox Deploy
on:
  workflow_dispatch: null
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: us-east-1
          role-to-assume: arn:aws:iam::758455838209:role/GithubFrontendDeployer
          role-skip-session-tagging: true
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.2
        with:
          node-version: 16
      - name: Build Application Package
        run: |
          npm install
          npm update @listen360/alexandria @listen360/js_api_client
          npm run build:sandbox
      - name: Upload dist to S3 bucket
        run: >
          aws s3 sync ./dist s3://reports-sandbox.listen360.com --acl public-read --delete
      - name: Invalidate Cloudfront
        run: >
          aws cloudfront create-invalidation --distribution-id ${{secrets.AWS_SANDBOX_CF_DISTRIBUTION }} --paths "/*"
      - name: Purge Cloudflare Cache
        uses: nathanvaughn/actions-cloudflare-purge@master
        if: success()
        with:
          cf_zone: ${{ secrets.CLOUDFLARE_ZONE }}
          cf_auth: ${{ secrets.CLOUDFLARE_AUTH_KEY }}
